from distutils.core import setup

setup(name='BlueCatClient',
      version='0.0.1',
      description='An API wrapper to work with BlueCat Networks - Adaptive DNS',
      author='Victor M Santiago',
      author_email='vsantiago113sec@gmail.com',
      url='https://github.com/vsantiago113',
      download_url='https://github.com/vsantiago113/BlueCatClient',
      license='MIT',
      packages=['BlueCatClient'],
      classifiers=[
          'Development Status :: 5 - Production/Stable',
          'Topic :: Utilities',
          'License :: OSI Approved :: MIT License',
          'Operating System :: MacOS :: MacOS X',
          'Operating System :: Microsoft :: Windows',
          'Operating System :: POSIX :: Linux',
          'Programming Language :: Python',
          'Intended Audience :: Developers',
          'Programming Language :: Python :: 3.4',
          'Programming Language :: Python :: 3.5',
          'Programming Language :: Python :: 3.6',
          'Programming Language :: Python :: 3.7',
          'Programming Language :: Python :: 3.8',
      ],
      install_requires=[
          'requests>=2.22.0',
          'urllib3>=1.25.3',
      ],
      python_requires='>=3.4.0',
      )
